apiVersion: apps/v1
kind: Deployment
metadata:
  name: kennedy-yolo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: client
        image: kipanch/yolo-client:v1.0.3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kennedy-yolo-client
spec:
  type: LoadBalancer
  selector:
    app: yolo-client
  ports:
  - port: 3000
    targetPort: 3000
